const state={mobs:[],items:[],skills:[],mobskills:{},mobloot:{},lootsets:{},loottables:{},spawns:[],zones:[],scripts:{},mode:'npc',selected:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fmt=n=>typeof n==='number'?n.toLocaleString(undefined,{maximumFractionDigits:2}):n;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const getMob=id=>state.mobs.find(m=>String(m.id)===String(id));
async function load(){
 const files=['mobs','items','skills','mobskills','mobloot','lootsets','loottables','spawns','zones','mobscripts'];
 const vals=await Promise.all(files.map(f=>fetch(`data/${f}.json`).then(r=>r.json())));
 files.forEach((f,i)=>state[f]=vals[i]);
 $('#mobCount').textContent=state.mobs.length.toLocaleString();
 renderResults();
}
function setMode(mode){state.mode=mode;state.selected=null;$$('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('#itemSearch').checked=mode==='item';$('#autoSearch').checked=mode!=='loot';$('#searchInput').value='';$('#idInput').value='';renderResults();clearDossier();}
function searchTerm(){return $('#searchInput').value.trim().toLowerCase()}
function renderResults(){
 const term=searchTerm(), id=$('#idInput').value.trim(); let arr=[];
 if(state.mode==='npc') arr=state.mobs.filter(m=>(!term||m.name.toLowerCase().includes(term))&&(!id||String(m.id)===id));
 else if(state.mode==='item') arr=state.items.filter(x=>(!term||x.name.toLowerCase().includes(term))&&(!id||String(x.id)===id));
 else { const entries=Object.keys(state.lootsets).map(Number); arr=entries.map(id=>({id,name:`Loot Set ${id}`,tables:state.lootsets[id].length})).filter(x=>(!term||x.name.toLowerCase().includes(term)||String(x.id).includes(term))&&(!id||String(x.id)===id)); }
 arr=arr.slice(0,250); $('#resultCount').textContent=arr.length;
 $('#results').innerHTML=arr.length?arr.map((x,i)=>`<div class="result ${state.selected&&String(state.selected.id)===String(x.id)?'active':''}" data-id="${x.id}"><div class="result-main"><div class="result-name">${esc(x.name)}</div><div class="result-meta">${state.mode==='npc'?`Lv ${fmt(x.level)} • ${esc(x.faction)}`:state.mode==='item'?`Item ID ${x.id}`:`${x.tables} loot tables`}</div></div><span class="badge">${x.id}</span></div>`).join(''):`<div style="padding:35px 18px;text-align:center;color:var(--muted);font-size:12px">No results found.<br><span style="font-size:10px">Try a shorter search term.</span></div>`;
 $$('.result').forEach(el=>el.onclick=()=>{const x=state.mode==='npc'?getMob(el.dataset.id):state.mode==='item'?state.items.find(i=>String(i.id)===el.dataset.id):{id:Number(el.dataset.id),name:`Loot Set ${el.dataset.id}`};state.selected=x;renderResults();if(state.mode==='npc')renderDossier(x);else if(state.mode==='item')renderItem(x);else openLootSet(x.id);});
}
function clearDossier(){$('#dossier').classList.add('hidden');$('#emptyState').classList.remove('hidden')}
function renderDossier(m){$('#emptyState').classList.add('hidden');const d=$('#dossier');d.classList.remove('hidden');
 const skills=(state.mobskills[m.id]||[]).map(s=>({...s,meta:state.skills.find(x=>x.id===s.skillId)}));
 const loot=state.mobloot[m.id]||[]; const spawns=state.spawns.filter(s=>s.mobs.some(x=>x.mobId===Number(m.id)));
 d.innerHTML=`<div class="dossier-head"><div><div class="title-row"><h2>${esc(m.name)}</h2><span class="id-pill">ID ${m.id}</span></div><div class="subline"><span class="faction ${m.faction.toLowerCase()}">${esc(m.faction)}</span><span>Level ${fmt(m.level)}</span><span>•</span><span>${spawns.length} spawn point${spawns.length===1?'':'s'}</span></div></div><div class="actions">${spawns.length?'<button class="action-btn" id="spawnBtn">⌖ Spawn Data</button>':''}${state.scripts[m.id]?'<button class="action-btn" id="scriptBtn">⌘ Script Data</button>':''}</div></div>
 <div class="grid stats-grid">${stat('Health',m.health,'HP')}${stat('Energy',m.energy,'Energy')}${stat('Attack',m.attack)}${stat('Defence',m.defence)}${stat('Attack Speed',m.attackSpeed,'ms')}${stat('Aggro Range',m.aggro)}${stat('Follow Range',m.follow)}${stat('Radius',m.radius)}</div>
 <div class="section"><div class="section-head"><div class="section-title">Combat profile</div></div><div class="cards"><div class="panel"><h3>Core values</h3><div class="kv">${kv('Experience',fmt(m.experience))}${kv('Gold dropped',m.gold)}${kv('Ignore invisibility',`${fmt(m.ignoreInvis*10)}% chance`)}${kv('AI type',fmt(m.aiType))}${kv('Attack / missile',esc(m.rangeData))}${kv('Database field',fmt(m.field21))}</div></div><div class="panel"><h3>Resistances</h3><div class="chips">${Object.entries(m.resist).map(([k,v])=>`<span class="chip">${esc(k)} <b>${esc(fmt(v))}</b></span>`).join('')}</div></div></div></div>
 <div class="section"><div class="section-head"><div class="section-title">Attack evasion</div></div><div class="panel"><div class="chips">${Object.entries(m.evasion).map(([k,v])=>`<span class="chip">${esc(k)} <b>${esc(fmt(v))}</b></span>`).join('')||'<span class="muted" style="padding:12px">No evasion data.</span>'}</div></div></div>
 <div class="section"><div class="section-head"><div class="section-title">Abilities</div><span class="muted" style="font-size:10px">${skills.length} linked skill${skills.length===1?'':'s'}</span></div><div class="panel">${skills.length?'<div class="list">'+skills.map(s=>`<div class="list-row"><div><b>${esc(s.meta?.name||`Skill ${s.skillId}`)}</b><div class="muted">${esc(s.meta?.damageType||'')} ${s.meta?.target?'• '+esc(s.meta.target):''}</div></div><span class="badge">Lv ${fmt(s.level)}</span></div>`).join('')+'</div>':'<div style="padding:16px;color:var(--muted);font-size:12px">No linked abilities in the database.</div>'}</div></div>
 <div class="section"><div class="section-head"><div class="section-title">Loot</div><span class="muted" style="font-size:10px">${loot.length} loot set link${loot.length===1?'':'s'}</span></div><div class="panel">${loot.length?'<div class="list">'+loot.map(l=>`<div class="list-row loot-set" data-loot="${l.setId}"><div><b>Loot Set ${l.setId}</b><div class="muted">Click to inspect tables</div></div><span class="badge">×${fmt(l.weight)}</span></div>`).join('')+'</div>':'<div style="padding:16px;color:var(--muted);font-size:12px">No direct loot-set mapping found for this NPC.</div>'}</div></div>
 <div class="footer-note">Data sourced from the supplied Master's Grimoire v5.10 database. Some internal fields are intentionally kept compact where the original program uses encoded values.</div>`;
 $$('.loot-set').forEach(x=>x.onclick=()=>openLootSet(Number(x.dataset.loot)));
 if($('#spawnBtn')) $('#spawnBtn').onclick=()=>openSpawns(m,spawns);
 if($('#scriptBtn')) $('#scriptBtn').onclick=()=>openScript(m);
}
function stat(k,v,u=''){return `<div class="stat"><div class="k">${k}</div><div class="v">${esc(fmt(v))}</div>${u?`<small>${u}</small>`:''}</div>`}function kv(k,v){return `<div><div class="k">${k}</div><div class="v">${v}</div></div>`}
function renderItem(x){$('#emptyState').classList.add('hidden');const d=$('#dossier');d.classList.remove('hidden');d.innerHTML=`<div class="dossier-head"><div><div class="title-row"><h2>${esc(x.name)}</h2><span class="id-pill">ID ${x.id}</span></div><div class="subline"><span>Item database entry</span></div></div></div><div class="section"><div class="panel"><h3>Description</h3><div style="padding:16px;color:var(--muted);line-height:1.6;font-size:13px">${esc(x.description)||'No description stored.'}</div></div></div>`}
function openLootSet(id){const tables=state.lootsets[id]||[];const total=tables.reduce((a,b)=>a+b.weight,0);$('#modal').classList.remove('hidden');$('#modalBody').innerHTML=`<div class="eyebrow">LOOT SET</div><h2 style="margin:0 0 5px">Loot Set ${id}</h2><p class="muted" style="margin:0">${tables.length} table${tables.length===1?'':'s'} • weights normalized to percentage.</p><div class="panel" style="margin-top:18px"><div class="list">${tables.map(t=>{const pct=total?t.weight/total*100:0,tab=state.loottables[t.tableId]||{name:`Table ${t.tableId}`,items:[]};return `<div class="list-row" data-table="${t.tableId}"><div style="min-width:0;flex:1"><b>${esc(tab.name)}</b><div class="muted">Table ${t.tableId} • weight ${fmt(t.weight)}</div><div class="mini-bar"><span style="width:${Math.min(100,pct)}%"></span></div></div><span class="badge" style="margin-left:15px">${pct.toFixed(2)}%</span></div>`}).join('')}</div></div>`;$$('[data-table]').forEach(x=>x.onclick=()=>openLootTable(Number(x.dataset.table)));}
function openLootTable(id){const t=state.loottables[id]||{name:`Table ${id}`,items:[]};const total=t.items.reduce((a,b)=>a+b.chance,0);$('#modalBody').innerHTML=`<div class="eyebrow">LOOT TABLE</div><h2 style="margin:0 0 5px">${esc(t.name)}</h2><p class="muted">Table ${id} • ${t.items.length} item entries</p><div class="panel" style="margin-top:18px"><div class="list">${t.items.map(it=>{const pct=total?it.chance/total*100:0,n=state.items.find(x=>x.id===it.itemId)?.name||`Item ${it.itemId}`;return `<div class="list-row"><div><b>${esc(n)}</b><div class="muted">ID ${it.itemId} • quantity ${esc(it.quantity)}</div></div><span class="badge">${pct.toFixed(2)}%</span></div>`}).join('')||'<div style="padding:15px;color:var(--muted)">No item entries.</div>'}</div></div><button class="action-btn" style="margin-top:14px" id="backLoot">← Back to loot set</button>`;$('#backLoot').onclick=()=>openLootSet(findLootSetForTable(id));}
function findLootSetForTable(id){for(const [sid,arr] of Object.entries(state.lootsets))if(arr.some(x=>x.tableId===id))return Number(sid);return 0}
function openScript(m){const rows=state.scripts[m.id]||[];$('#modal').classList.remove('hidden');$('#modalBody').innerHTML=`<div class="eyebrow">SCRIPT DATA</div><h2 style="margin:0 0 5px">${esc(m.name)}</h2><p class="muted">Raw script records linked to NPC ${m.id}.</p><pre style="white-space:pre-wrap;background:#090c12;border:1px solid var(--line);padding:16px;border-radius:12px;color:#bfc7d6;font-size:11px;line-height:1.55">${esc(rows.map(r=>r.join('  ~  ')).join('\n'))}</pre>`}
function openSpawns(m,spawns){const zmap={};state.zones.forEach(z=>zmap[z.id]=z);const grouped=defaultdict(spawns,s=>s.zone);let first=spawns[0],zone=zmap[first.zone],map=`maps/${zone?.map||''}.jpg`;$('#modal').classList.remove('hidden');$('#modalBody').innerHTML=`<div class="eyebrow">SPAWN DATA</div><h2 style="margin:0 0 5px">${esc(m.name)}</h2><p class="muted">${spawns.length} spawn point${spawns.length===1?'':'s'} across ${new Set(spawns.map(s=>s.zone)).size} zone${new Set(spawns.map(s=>s.zone)).size===1?'':'s'}.</p><div class="spawn-grid">${spawns.slice(0,24).map((s,i)=>{const zz=zmap[s.zone];return `<div class="spawn-card" data-spawn-index="${i}" style="cursor:pointer"><b>${esc(zz?.name||`Zone ${s.zone}`)}</b><span>Spawn ${s.id} • ${esc(s.respawn)} • ${s.behavior}</span><div style="margin-top:6px;font-size:10px;color:#c8bcff">X ${s.x.toFixed(2)} • Y ${s.y.toFixed(2)} • Z ${s.z.toFixed(2)}</div></div>`}).join('')}</div><div class="map-wrap"><img id="spawnMap" src="${map}" alt="Zone map" onerror="this.style.display='none'"><div id="mapDots"></div></div>`;renderMapDots(spawns,zone);$$('[data-spawn-index]').forEach(el=>el.onclick=()=>{const s=spawns[Number(el.dataset.spawnIndex)];zone=zmap[s.zone];$('#spawnMap').src=`maps/${zone?.map||''}.jpg`;renderMapDots(spawns.filter(x=>x.zone===s.zone),zone)});}
function defaultdict(arr,key){const o={};arr.forEach(x=>(o[key(x)]??=[]).push(x));return o}
function renderMapDots(spawns,zone){const box=$('#mapDots');if(!box)return;box.innerHTML='';if(!zone)return;const w=zone.maxX-zone.minX,h=zone.maxZ-zone.minZ;spawns.forEach(s=>{const d=document.createElement('div');d.className='spawn-dot';d.style.left=((s.x-zone.minX)/w*100)+'%';d.style.top=((s.z-zone.minZ)/h*100)+'%';d.title=`Spawn ${s.id}`;box.appendChild(d)})}
$('#searchInput').addEventListener('input',renderResults);$('#idSearch').onclick=renderResults;$('#idInput').addEventListener('keydown',e=>{if(e.key==='Enter')renderResults()});$('#clearSearch').onclick=()=>{$('#searchInput').value='';renderResults();$('#searchInput').focus()};$('#autoSearch').onchange=()=>{};$('#itemSearch').onchange=()=>{setMode($('#itemSearch').checked?'item':'npc')};$$('.mode').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-close]').forEach(x=>x.onclick=()=>$('#modal').classList.add('hidden'));$('#themeBtn').onclick=()=>document.body.classList.toggle('light');
load().catch(err=>{$('#results').innerHTML='<div style="padding:20px;color:#ff9aaa;font-size:12px">Could not load the database. Make sure all files are uploaded to GitHub and GitHub Pages is serving the repository.</div>';console.error(err)});
